trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'AdventurerClientDotNet.Console\AdventurerClientDotNet.Console.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) -r win-x64 --output $(Build.ArtifactStagingDirectory)/Console/win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true'
    zipAfterPublish: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'AdventurerClientDotNet.Console\AdventurerClientDotNet.Console.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) -r osx-x64 --output $(Build.ArtifactStagingDirectory)/Console/osx-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'